spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: yongmall-ware

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
server:
  port: 9050
