spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: yongmall-product
  cloud:
    alicloud:
      access-key: LTAI5tGa8sPY7Y9JEHHbxfQ9
      accessKeySecret: JR0Pdmh9gr9al3kEvzC7mOmZLddYIN
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com

server:
  port: 6001


#mybatis-plus:
#  global-config:
#    db-config:
#      logic-delete-field: showStatus # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)

