spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: yongmall-memeber

server:
  port: 8000
