spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.226.1:8848
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,qq

        - id: path_route
          uri: https://www.qq.com
          predicates:
            - Path=/red/{segment}
  application:
    name: gateway



server:
  port: 8079

