spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    gateway:
      routes:
        - id: product-server
          uri: localhost:6001/
          predicates:
            - Path=/product/**
      enabled: true

  application:
    name: gateway



server:
  port: 8079

